import os
from uuid import UUID

from fastapi import APIRouter, HTTPException, Request
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates

import api.data
from api.models import ProcurementRequest, RequestStatus

templates = Jinja2Templates(directory="html")
router = APIRouter()

# Serve React app static files
frontend_dist_path = os.path.join(os.path.dirname(__file__), "..", "frontend", "dist")
if os.path.exists(frontend_dist_path):
    # Mount the static files for the React app
    router.mount(
        "/", StaticFiles(directory=frontend_dist_path, html=True), name="frontend"
    )


@router.get("/")
async def index(request: Request):
    return templates.TemplateResponse(request=request, name="index.html", context={})


@router.get("/requests")
async def get_requests():
    return api.data.get_requests()


@router.get("/request/{request_id}")
async def get_request(request_id: UUID):
    request = api.data.get_request_by_id(request_id)
    if not request:
        raise HTTPException(status_code=404, detail="Request not found")
    return request


@router.post("/request/new")
async def add_request(request: ProcurementRequest):
    # Ensure the ID is generated by the model if not provided
    success: bool = api.data.add_request(request)
    if not success:
        raise HTTPException(status_code=500, detail="request could not be created")

    return {"message": "Request created", "id": request.id}


@router.put("/request/{request_id}/status")
async def update_request_status(request_id: UUID, status: RequestStatus):
    success: bool = api.data.update_request_status(request_id, status)
    if not success:
        raise HTTPException(
            status_code=404, detail="Request not found or could not be updated"
        )

    return {"message": f"Request status updated to {status}"}
