from uuid import UUID

from fastapi import APIRouter, File, HTTPException, Request, UploadFile
from fastapi.templating import Jinja2Templates

import api.data
from api.models import ProcurementRequest, StatusUpdate
from api.openai import extract_procurement_request

templates = Jinja2Templates(directory="html")
router = APIRouter()


@router.get("/")
async def index(request: Request):
    return templates.TemplateResponse(request=request, name="index.html", context={})


@router.get("/requests")
async def get_requests():
    return api.data.get_requests()


@router.get("/request/{request_id}")
async def get_request(request_id: UUID):
    request = api.data.get_request_by_id(request_id)
    if not request:
        raise HTTPException(status_code=404, detail="Request not found")
    return request


@router.post("/request/new")
async def add_request(request: ProcurementRequest):
    # Ensure the ID is generated by the model if not provided
    success: bool = api.data.add_request(request)
    if not success:
        raise HTTPException(status_code=500, detail="request could not be created")

    return {"message": "Request created", "id": request.id}


@router.put("/request/{request_id}/status")
async def update_request_status(request_id: UUID, update: StatusUpdate):
    success: bool = api.data.update_request_status(request_id, update.status)
    if not success:
        raise HTTPException(
            status_code=404, detail="Request not found or could not be updated"
        )

    return {"message": f"Request status updated to {update.status}"}


@router.post("/extract")
async def extract(file: UploadFile = File(...)):
    if file.content_type not in ("application/pdf", "application/octet-stream"):
        raise HTTPException(status_code=400, detail="Only PDF files are supported")

    pdf_bytes = await file.read()
    request = await extract_procurement_request(
        pdf_bytes, file.filename or "request.pdf"
    )
    return request
